# ------------------------------
# Kubernetes Service (k8s/service.yaml)
# ------------------------------

apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - port: 80
    targetPort: 8501
    nodePort: 30001