# ------------------------------
# GitHub Actions Workflow (.github/workflows/deploy.yml)
# ------------------------------

name: CI/CD Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  IMAGE_NAME: ${{ secrets.DOCKER_USER }}/ai-app-cicd

jobs:
  sonarqube-analysis:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (required for Sonar Scanner)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Wait for SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


  build:
    needs: sonarqube-analysis
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build --tag $REGISTRY/$IMAGE_NAME:latest --load .

  scan:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Scan Docker image with Trivy and save report
        run: |
          mkdir -p trivy-results
          trivy image --exit-code 1 --severity CRITICAL,HIGH --format json --output trivy-results/scan.json $REGISTRY/$IMAGE_NAME:latest

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-results/scan.json



  push:
    needs: scan
    runs-on: self-hosted

    steps:
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    needs: push
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
